//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MouseSteeringWheel.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MouseSteeringWheel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Button Hotkey 的本地化字符串。
        /// </summary>
        public static string ButtonHotkeyName {
            get {
                return ResourceManager.GetString("ButtonHotkeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Button Key Binding 的本地化字符串。
        /// </summary>
        public static string ButtonKeyBindingName {
            get {
                return ResourceManager.GetString("ButtonKeyBindingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string CancelName {
            get {
                return ResourceManager.GetString("CancelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deadzone 的本地化字符串。
        /// </summary>
        public static string DeadzoneName {
            get {
                return ResourceManager.GetString("DeadzoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The percentage of the joystick dead zone, ranging from 0-100 的本地化字符串。
        /// </summary>
        public static string DeadzoneTooltip {
            get {
                return ResourceManager.GetString("DeadzoneTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable 的本地化字符串。
        /// </summary>
        public static string EnableName {
            get {
                return ResourceManager.GetString("EnableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string ErrorPopTitle {
            get {
                return ResourceManager.GetString("ErrorPopTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string GeneralName {
            get {
                return ResourceManager.GetString("GeneralName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click &amp; Press Keys to Record 的本地化字符串。
        /// </summary>
        public static string HotkeyHintName {
            get {
                return ResourceManager.GetString("HotkeyHintName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hotkey 的本地化字符串。
        /// </summary>
        public static string HotkeyName {
            get {
                return ResourceManager.GetString("HotkeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The vJoy driver is not installed or initialized correctly. Please ensure that the vJoy driver is installed on the system. 的本地化字符串。
        /// </summary>
        public static string InitializationFailedContent {
            get {
                return ResourceManager.GetString("InitializationFailedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initialization failed 的本地化字符串。
        /// </summary>
        public static string InitializationFailedTitle {
            get {
                return ResourceManager.GetString("InitializationFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Joystick 的本地化字符串。
        /// </summary>
        public static string JoystickName {
            get {
                return ResourceManager.GetString("JoystickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language changes will take effect after saving the settings and restarting. 的本地化字符串。
        /// </summary>
        public static string LanguageTooltip {
            get {
                return ResourceManager.GetString("LanguageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nonlinear 的本地化字符串。
        /// </summary>
        public static string NonlinearName {
            get {
                return ResourceManager.GetString("NonlinearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A value of 1 represents linear movement. A value less than 1 results in more precise control of the outer circle. A value greater than 1 results in more precise control of the inner circle. 的本地化字符串。
        /// </summary>
        public static string NonlinearTooltip {
            get {
                return ResourceManager.GetString("NonlinearTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Settings 的本地化字符串。
        /// </summary>
        public static string OpenSettingsName {
            get {
                return ResourceManager.GetString("OpenSettingsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause Joystick 的本地化字符串。
        /// </summary>
        public static string PauseJoystickName {
            get {
                return ResourceManager.GetString("PauseJoystickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hotkey registration failed! 的本地化字符串。
        /// </summary>
        public static string RegistHotKeyFailedPop {
            get {
                return ResourceManager.GetString("RegistHotKeyFailedPop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset Joystick 的本地化字符串。
        /// </summary>
        public static string ResetJoystickName {
            get {
                return ResourceManager.GetString("ResetJoystickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset the mouse position to the center of the screen and the joystick position to the center. 的本地化字符串。
        /// </summary>
        public static string ResetJoystickTooltip {
            get {
                return ResourceManager.GetString("ResetJoystickTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string SaveName {
            get {
                return ResourceManager.GetString("SaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sensitivity 的本地化字符串。
        /// </summary>
        public static string SensitivityName {
            get {
                return ResourceManager.GetString("SensitivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A multiple of the joystick movement value for every 1 pixel of mouse movement. vJoy joystick movement values range from 0 to 32767. values must be positive integers. 的本地化字符串。
        /// </summary>
        public static string SensitivityTooltip {
            get {
                return ResourceManager.GetString("SensitivityTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string SettingsWindowName {
            get {
                return ResourceManager.GetString("SettingsWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steering Wheel 的本地化字符串。
        /// </summary>
        public static string SteeringWheelName {
            get {
                return ResourceManager.GetString("SteeringWheelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scale Factor 的本地化字符串。
        /// </summary>
        public static string UIScaleFactorName {
            get {
                return ResourceManager.GetString("UIScaleFactorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controls the UI scale, a value greater than 1 means scale up, a value less than 1 means scale down. 的本地化字符串。
        /// </summary>
        public static string UIScaleFactorTooltip {
            get {
                return ResourceManager.GetString("UIScaleFactorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Style 的本地化字符串。
        /// </summary>
        public static string UIStyleName {
            get {
                return ResourceManager.GetString("UIStyleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y-Axis Offset 的本地化字符串。
        /// </summary>
        public static string UIYAxisOffset {
            get {
                return ResourceManager.GetString("UIYAxisOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only in effect when the UI style is joystick, which controls the position of the joystick UI in the vertical direction of the screen. The bottom of the screen is the zero point. 的本地化字符串。
        /// </summary>
        public static string UIYAxisOffsetTooltip {
            get {
                return ResourceManager.GetString("UIYAxisOffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hotkeys that correspond to vJoy buttons. vJoy supports a maximum of 128 buttons, so make sure you have enabled the corresponding number of buttons in vJoy. 的本地化字符串。
        /// </summary>
        public static string vJoyButtonIDTooltip {
            get {
                return ResourceManager.GetString("vJoyButtonIDTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The currently specified vJoy device is busy, please check whether it is occupied by other programs. 的本地化字符串。
        /// </summary>
        public static string vJoyDeviceBusyContent {
            get {
                return ResourceManager.GetString("vJoyDeviceBusyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vJoy Device Busy 的本地化字符串。
        /// </summary>
        public static string vJoyDeviceBusyTitle {
            get {
                return ResourceManager.GetString("vJoyDeviceBusyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vJoy Device ID 的本地化字符串。
        /// </summary>
        public static string vJoyDeviceIDName {
            get {
                return ResourceManager.GetString("vJoyDeviceIDName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the vJoy device ID to be used, in the range of 0 to 16, making sure that the corresponding device is enabled in vJoy. Changes will take effect after a restart. 的本地化字符串。
        /// </summary>
        public static string vJoyDeviceIDTooltip {
            get {
                return ResourceManager.GetString("vJoyDeviceIDTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified device was not found 的本地化字符串。
        /// </summary>
        public static string vJoyDeviceNotFoundContent {
            get {
                return ResourceManager.GetString("vJoyDeviceNotFoundContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vJoy Device Not Found 的本地化字符串。
        /// </summary>
        public static string vJoyDeviceNotFoundTitle {
            get {
                return ResourceManager.GetString("vJoyDeviceNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vJoy Device Obtain Failed, , please check whether it is occupied by other programs. 的本地化字符串。
        /// </summary>
        public static string vJoyDeviceObtainFailedContent {
            get {
                return ResourceManager.GetString("vJoyDeviceObtainFailedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vJoy Device Obtain Failed 的本地化字符串。
        /// </summary>
        public static string vJoyDeviceObtainFailedTitle {
            get {
                return ResourceManager.GetString("vJoyDeviceObtainFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vJoy Device General Error 的本地化字符串。
        /// </summary>
        public static string vJoyErrorContent {
            get {
                return ResourceManager.GetString("vJoyErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vJoy Error 的本地化字符串。
        /// </summary>
        public static string vJoyErrorTitle {
            get {
                return ResourceManager.GetString("vJoyErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vJoy version mismatch. Please use version 2.2.2.0. 的本地化字符串。
        /// </summary>
        public static string vJoyVersionMismatchContent {
            get {
                return ResourceManager.GetString("vJoyVersionMismatchContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vJoy version mismatch 的本地化字符串。
        /// </summary>
        public static string vJoyVersionMismatchTitle {
            get {
                return ResourceManager.GetString("vJoyVersionMismatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X-axis not detected, make sure X-axis is enabled in vJoy 的本地化字符串。
        /// </summary>
        public static string vJoyXAxisNotDetectedContent {
            get {
                return ResourceManager.GetString("vJoyXAxisNotDetectedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vJoy X Axis Not Detected 的本地化字符串。
        /// </summary>
        public static string vJoyXAxisNotDetectedTitle {
            get {
                return ResourceManager.GetString("vJoyXAxisNotDetectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y-axis not detected, make sure Y-axis is enabled in vJoy 的本地化字符串。
        /// </summary>
        public static string vJoyYAxisNotDetectedContent {
            get {
                return ResourceManager.GetString("vJoyYAxisNotDetectedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vJoy Y Axis Not Detected 的本地化字符串。
        /// </summary>
        public static string vJoyYAxisNotDetectedTitle {
            get {
                return ResourceManager.GetString("vJoyYAxisNotDetectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X-Axis 的本地化字符串。
        /// </summary>
        public static string XAxisName {
            get {
                return ResourceManager.GetString("XAxisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y-Axis 的本地化字符串。
        /// </summary>
        public static string YAxisName {
            get {
                return ResourceManager.GetString("YAxisName", resourceCulture);
            }
        }
    }
}
